### ISSUE TITLE
Response now contains a zip file

### ISSUE THREAD

**Issue by andrepiresrep** [MicrosoftDocs/partner-rest#2] opened 2020-04-28 12:30 UTC
Hello,
Since today content of the response now comes with a zip file instead of the csv file.
It would be important to mention this on the documentation.
Also what is the encoding of the zip file and the csv file?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86441aa8-87fb-4424-0335-8c6d77a0f072
* Version Independent ID: 5e462b29-f12f-e424-3b33-1cc239a793e7
* Content: [Get a price sheet - Partner](https://docs.microsoft.com/en-us/partner/develop/get-a-price-sheet)
* Content Source: [partner-rest/develop/get-a-price-sheet.md](https://github.com/MicrosoftDocs/partner-rest/blob/docs/partner-rest/develop/get-a-price-sheet.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-sdk**
* GitHub Login: @JasonWHowell
* Microsoft Alias: **jasonh**

**Comment by JasonWHowell** [comment] 2020-09-16 02:45
Duplicate of #3 which has additional feedback. Closing this one as a duplicate. #please-close

**Closed as completed** 2020-09-16 02:45 UTC
